# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl40BzMlcMXK6rvf8BEMSb-go66h0v2z
"""

import os
import feedparser
import requests
from google import genai


# Get secrets from GitHub Actions
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = os.getenv("CHANNEL_ID")
GEMINI_KEY = os.getenv("GEMINI_KEY")
CHANNEL_ID_2 = os.getenv("CHANNEL_ID_2")


RSS_FEEDS = [
    "https://feeds.marketwatch.com/marketwatch/topstories/",
    "https://www.coindesk.com/arc/outboundfeeds/rss/",
    "https://www.investing.com/rss/news.rss",
    "https://feeds.reuters.com/reuters/businessNews",
    "https://feeds.reuters.com/reuters/globalmarketsNews",
]


def get_news():
    articles = []

    for feed_url in RSS_FEEDS:
        try:
            feed = feedparser.parse(feed_url)

            if not hasattr(feed, "entries"):
                continue

            for entry in feed.entries[:3]:
                if hasattr(entry, "title") and hasattr(entry, "link"):
                    articles.append({
                        "title": entry.title,
                        "link": entry.link
                    })

        except Exception as e:
            print(f"RSS failed: {feed_url} -> {e}")

    return articles

def summarize_news(articles):

    headlines = "\n".join(
        f"- {article['title']}"
        for article in articles
    )

    prompt = f"""
You are a professional global macroeconomic news editor writing for a Telegram audience of students and finance enthusiasts.

Task:
1. Read all provided headlines.
2. First, classify them into these categories:
   - Central Banks & Interest Rates
   - Inflation & Macroeconomy (GDP, jobs, CPI)
   - Stock Markets & Corporate News
   - Crypto & Digital Assets
   - Energy & Commodities (oil, gas, gold)
   - Global Trade, Geopolitics & Policy

3. From EACH category, select the most important and market-moving story (if available).
4. If a category has no meaningful news, skip it.

Output format:

🌍 Global Economic News Brief 💰📈

Central Banks & Rates
1. Title of story + 1–2 relevant emojis only
Short but informative explanation (2–3 sentences). Include key numbers if available and explain market impact.

Inflation & Macroeconomy
2. Title of story + 1–2 relevant emojis only
Short explanation (2–3 sentences) with context and economic impact.

Stock Markets & Corporate News
3. Title of story + 1–2 relevant emojis only
Short explanation (2–3 sentences) focusing on market reaction and implications.

Crypto & Digital Assets
4. Title of story + 1–2 relevant emojis only
Short explanation (2–3 sentences) focusing on price/market impact.

Energy & Commodities
5. Title of story + 1–2 relevant emojis only
Short explanation (2–3 sentences).

Global Trade, Geopolitics & Policy
6. Title of story + 1–2 relevant emojis only
Short explanation (2–3 sentences).

📌 Market Summary:
Write 2–3 sentences summarizing overall global market sentiment (risk-on / risk-off), key drivers, and what investors should watch next.

Rules:
- Maximum 200–250 words total.
- Clear, professional English (not too academic, not casual).
- Do NOT invent data.
- Merge duplicate stories across sources.
- Each category must use different emojis.
- Emojis must match topic meaning:
  - Inflation / macro → 📊📈💹
  - Central banks / rates → 🏦💰
  - Stocks / markets → 📉📈💼
  - Crypto → ₿🚀🪙
  - Energy / commodities → 🛢️⚡
  - Risk / uncertainty → ⚠️🌍
  - Tech / companies → 🤖💻🚀
- Focus on market impact, not just description.

Make it feel like a Bloomberg-style daily briefing for Telegram.

Headlines:
{headlines}
"""

    client = genai.Client(api_key=GEMINI_KEY)

    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )

    return response.text

def send_to_telegram(message):

    url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

    for chat_id in [CHANNEL_ID, CHANNEL_ID_2]:

        payload = {
            "chat_id": chat_id,
            "text": message
        }

        result = requests.post(
            url,
            json=payload
        )

        print(result.json())


def main():

    print("Getting news...")

    articles = get_news()

    print(f"Found {len(articles)} articles")

    summary = summarize_news(articles)

    print("Summary created")

    send_to_telegram(summary)

    print("Posted to Telegram")


if __name__ == "__main__":
    main()
