# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hl40BzMlcMXK6rvf8BEMSb-go66h0v2z
"""

import os
import feedparser
import requests
from google import genai


# Get secrets from GitHub Actions
BOT_TOKEN = os.getenv("BOT_TOKEN")
CHANNEL_ID = os.getenv("CHANNEL_ID")
GEMINI_KEY = os.getenv("GEMINI_KEY")


RSS_FEEDS = [
    "https://feeds.bbci.co.uk/news/world/rss.xml",
    "https://feeds.bbci.co.uk/news/business/rss.xml",
]


def get_news():
    articles = []

    for feed_url in RSS_FEEDS:
        feed = feedparser.parse(feed_url)

        for entry in feed.entries[:5]:
            articles.append({
                "title": entry.title,
                "link": entry.link
            })

    return articles


def summarize_news(articles):

    headlines = "\n".join(
        [
            f"- {article['title']}"
            for article in articles
        ]
    )

    prompt = f"""
Create a professional Telegram daily news digest.

Rules:
- Add a short title
- Use 5 bullet points
- Simple language
- Maximum 300 words
- Add important source links at the end

News:

{headlines}
"""

    client = genai.Client(api_key=GEMINI_KEY)

    response = client.models.generate_content(model="gemini-2.5-flash", contents=prompt)

    return response.text


def send_to_telegram(message):

    url = (
        f"https://api.telegram.org/"
        f"bot{BOT_TOKEN}/sendMessage"
    )

    payload = {
        "chat_id": CHANNEL_ID,
        "text": message
    }

    result = requests.post(
        url,
        json=payload
    )

    print(result.json())


def main():

    print("Getting news...")

    articles = get_news()

    print(f"Found {len(articles)} articles")

    summary = summarize_news(articles)

    print("Summary created")

    send_to_telegram(summary)

    print("Posted to Telegram")


if __name__ == "__main__":
    main()