# -*- coding: utf-8 -*-
"""shsh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LdYdD6p1XlIFnS0uN-jz3oP3ZuXeDpAA
"""

!pip install feedparser openai requests

BOT_TOKEN = "8671511076:AAFxDuCdFuI01TmOYfIiZfRqHXaxwLnSdWA"
CHANNEL_ID = "-1004369073577"
OPENAI_API_KEY = "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"

import feedparser

RSS_FEEDS = [
    "https://feeds.bbci.co.uk/news/world/rss.xml",
    "https://feeds.bbci.co.uk/news/business/rss.xml",
]

articles = []

for feed_url in RSS_FEEDS:
    feed = feedparser.parse(feed_url)

    for entry in feed.entries[:5]:
        articles.append({
            "title": entry.title,
            "link": entry.link
        })

headlines_text = ""

for article in articles:
    headlines_text += (
        f"- {article['title']}\n"
    )

prompt = f"""
Create a professional Telegram daily news digest.

Requirements:
- Short title
- 5 bullet points
- Simple language
- Under 300 words

Headlines:

{chr(10).join(headlines)}
"""

!pip install google-generativeai

import google.generativeai as genai

GEMINI_KEY = "AIzaSyB2FHJ5jeIqj-ZI5L4Pao53Srw_qv_YD24"

genai.configure(api_key=GEMINI_KEY)

model = genai.GenerativeModel("gemini-2.5-flash")

response = model.generate_content(prompt)

summary = response.text

print(summary)

import requests

url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"

payload = {
    "chat_id": CHANNEL_ID,
    "text": summary
}

response = requests.post(url, json=payload)

print(response.json())

